/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'IconBi:exclamationCircleFill': typeof import('~icons/bi/exclamation-circle-fill')['default']
    'IconClarity:timesCircleSolid': typeof import('~icons/clarity/times-circle-solid')['default']
    'IconClarity:timesLine': typeof import('~icons/clarity/times-line')['default']
    IconFaBrandsFacebookSquare: typeof import('~icons/fa-brands/facebook-square')['default']
    IconFaBrandsInstagram: typeof import('~icons/fa-brands/instagram')['default']
    IconFaBrandsTiktok: typeof import('~icons/fa-brands/tiktok')['default']
    IconFaBrandsYoutube: typeof import('~icons/fa-brands/youtube')['default']
    IconIcBaselineArrowForwardIos: typeof import('~icons/ic/baseline-arrow-forward-ios')['default']
    IconMaterialSymbolsAlternateEmail: typeof import('~icons/material-symbols/alternate-email')['default']
    IconMaterialSymbolsContactEmergency: typeof import('~icons/material-symbols/contact-emergency')['default']
    IconMaterialSymbolsContactEmergencyOutline: typeof import('~icons/material-symbols/contact-emergency-outline')['default']
    IconMaterialSymbolsDensityMediumRounded: typeof import('~icons/material-symbols/density-medium-rounded')['default']
    IconMaterialSymbolsPhoneAndroidOutline: typeof import('~icons/material-symbols/phone-android-outline')['default']
    'IconMdi:checkCircle': typeof import('~icons/mdi/check-circle')['default']
    'IconMdi:githubFace': typeof import('~icons/mdi/github-face')['default']
    'IconSimpleIcons:nuxtdotjs': typeof import('~icons/simple-icons/nuxtdotjs')['default']
    'IconUil:angleDown': typeof import('~icons/uil/angle-down')['default']
    'IconUil:apps': typeof import('~icons/uil/apps')['default']
    'IconUil:bars': typeof import('~icons/uil/bars')['default']
    'IconUil:clock': typeof import('~icons/uil/clock')['default']
    'IconUil:laptop': typeof import('~icons/uil/laptop')['default']
    'IconUil:moon': typeof import('~icons/uil/moon')['default']
    'IconUil:sun': typeof import('~icons/uil/sun')['default']
    'IconUil:times': typeof import('~icons/uil/times')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
