// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'Icon:ic:baselineArrowRightAlt': typeof import('~icons/ic/baseline-arrow-right-alt')['default']
    'IconBi:exclamationCircleFill': typeof import('~icons/bi/exclamation-circle-fill')['default']
    IconBiInstagram: typeof import('~icons/bi/instagram')['default']
    'IconClarity:timesCircleSolid': typeof import('~icons/clarity/times-circle-solid')['default']
    'IconClarity:timesLine': typeof import('~icons/clarity/times-line')['default']
    IconFaBrandsFacebookSquare: typeof import('~icons/fa-brands/facebook-square')['default']
    IconFaBrandsInstagram: typeof import('~icons/fa-brands/instagram')['default']
    IconFaBrandsTiktok: typeof import('~icons/fa-brands/tiktok')['default']
    IconFaBrandsYoutube: typeof import('~icons/fa-brands/youtube')['default']
    IconFluentMdl2FacebookLogo: typeof import('~icons/fluent-mdl2/facebook-logo')['default']
    IconFluentMdl2TwitterLogo: typeof import('~icons/fluent-mdl2/twitter-logo')['default']
    IconIcBaselineTiktok: typeof import('~icons/ic/baseline-tiktok')['default']
    IconLineMdInstagram: typeof import('~icons/line-md/instagram')['default']
    IconLineMdTwitterTwotone: typeof import('~icons/line-md/twitter-twotone')['default']
    IconLogosFacebook: typeof import('~icons/logos/facebook')['default']
    IconLogosInstagramIcon: typeof import('~icons/logos/instagram-icon')['default']
    IconMaterialSymbolsDensityMediumRounded: typeof import('~icons/material-symbols/density-medium-rounded')['default']
    'IconMdi:checkCircle': typeof import('~icons/mdi/check-circle')['default']
    'IconMdi:githubFace': typeof import('~icons/mdi/github-face')['default']
    IconMdiYoutube: typeof import('~icons/mdi/youtube')['default']
    IconRiInstagramLine: typeof import('~icons/ri/instagram-line')['default']
    'IconSimpleIcons:nuxtdotjs': typeof import('~icons/simple-icons/nuxtdotjs')['default']
    'IconUil:angleDown': typeof import('~icons/uil/angle-down')['default']
    'IconUil:apps': typeof import('~icons/uil/apps')['default']
    'IconUil:bars': typeof import('~icons/uil/bars')['default']
    'IconUil:clock': typeof import('~icons/uil/clock')['default']
    'IconUil:laptop': typeof import('~icons/uil/laptop')['default']
    'IconUil:moon': typeof import('~icons/uil/moon')['default']
    'IconUil:sun': typeof import('~icons/uil/sun')['default']
    'IconUil:times': typeof import('~icons/uil/times')['default']
    IconUiwFacebook: typeof import('~icons/uiw/facebook')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
