# for development only
# maybe remove when the project is finished
# because when the app is on production, the database should not be reset

name: Reset Database
# on prisma file changes
on:
  push:
    branches:
      - dev
    paths:
      - prisma/schema.prisma

jobs:
  resetDatabase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2.2.4
        name: install pnpm
        id: pnpm-install
        with:
          version: 7.27.0
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: pnpm install -g typescript ts-node @types/node prisma @prisma/client
      - name: create .env
        run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
      - name: remove import nuxt tsconfig.json
        run: sed -i '/extends/d' tsconfig.json
      - name: reset database
        run: pnpm database:reset
